from typing import Protocol

from nail_lab.domain.images import NailImage


class NailTransferGateway(Protocol):
    def upload(self, image: NailImage) -> str: ...
    def create_task(self, source_id: str, reference_id: str) -> str: ...
    def task_status(self, task_id: str) -> dict: ...
    def download_result(self, url: str) -> bytes: ...
